iBotPeaches/LeafApp_Infinite

resources/views/partials/global/footer.blade.php
Sticky footers are not my thing. So padding for now.
=> fix: add padding on footer

.env.example, README.md, app/Console/Commands/AddXuidToExistingAccounts.php, app/Models/Player.php, app/Providers/AppServiceProvider.php, app/Services/XboxApi/ApiClient.php, app/Services/XboxApi/XboxInterface.php, config/services.php, database/migrations/2021_11_25_111532_add_xuid_to_players.php
=> XUID Support

app/Models/Player.php, database/factories/PlayerFactory.php, tests/Feature/Pages/PlayerPageTest.php
=> Resolve gamertag w/ spaces

app/Models/Player.php, app/Models/ServiceRecord.php, database/migrations/2021_11_27_111516_add_is_private_to_players.php, resources/views/livewire/overview-page.blade.php, resources/views/pages/player.blade.php
=> Support Private Accounts

app/Models/Csr.php, resources/views/livewire/competitive-page.blade.php
=> Fix UI issue w/ Onyx accounts

app/Http/Livewire/UpdatePlayerPanel.php, app/Services/HaloDotApi/ApiClient.php, app/Services/HaloDotApi/InfiniteInterface.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
This will solve issues if the API is down during paginated match calls.
=> DB Transactions

app/Jobs/PullMatchHistory.php, app/Models/Player.php, config/queue.php, database/migrations/2021_11_29_123143_create_jobs_table.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
I thought there was a 100 game limit on API, so max of 4 API calls but this turns out to be false. As I saw some pro players searched and they were returning 300-400 games at 25 per page so it takes some time.
Now that is in background.
=> Jobs (Match History)

app/Models/GamePlayer.php
=> fix: revert workaround, fixed upstream

app/Models/Csr.php, tests/Unit/Models/CsrModelTest.php
=> Fix: Next Rank Onyx bug

composer.lock, resources/sass/app.scss, resources/views/layouts/app.blade.php, resources/views/partials/global/footer.blade.php
=> Fix-Sticky-Footer

app/Http/Livewire/UpdatePlayerPanel.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
=> Support filling missing XUID

app/Http/Livewire/UpdateGamePanel.php, app/Http/Livewire/UpdatePlayerPanel.php, app/Jobs/PullAppearance.php, app/Jobs/PullMatchHistory.php, app/Jobs/PullXuid.php, app/Models/Csr.php, app/Models/GamePlayer.php, app/Models/ServiceRecord.php
=> Lock DB during Player/Game Updates

app/Models/Player.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
=> Support Appearance Update (async)

app/Models/Player.php, app/Services/Autocode/ApiClient.php, database/migrations/2022_01_08_122126_add_last_game_id_to_players.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
=> Fix History Loading after adding PGCR

README.md, app/Models/GameTeam.php, package.json, resources/sass/app.scss, resources/views/livewire/game-history-table.blade.php, resources/views/partials/game/game-card.blade.php, resources/views/partials/game/team-table.blade.php, resources/views/partials/player/medals.blade.php, tests/Feature/Pages/GamePageTest.php, tests/Unit/Models/GameTeamModelTest.php, yarn.lock
=> Swap to Bulma Tooltips

tests/Feature/Forms/UpdateGamePanel/ValidGameUpdateTest.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
Thanks to https://github.com/livewire/livewire/pull/4336, maybe in the future it can accept the FQNS so I don't have to use magic strings.
=> test: add new assertEmittedTo

app/Http/Livewire/UpdatePlayerPanel.php, app/Models/Player.php
=> fix: make game history pull async (if not on game history page)

app/Http/Livewire/GamePage.php
=> fix: prevent medals changing due to async match history

app/Http/Livewire/GamePage.php, resources/views/livewire/game-page.blade.php
Autocode no longer returns this data, so this feature is bugged. Show all medals till we can filter down.
=> Fix medal showing

app/Jobs/PullMatchHistory.php, app/Jobs/PullXuid.php, app/Observers/PlayerObserver.php, database/migrations/2021_11_21_175835_add_matches_table.php, database/migrations/2021_11_26_111551_add_competitive_table.php, database/migrations/2021_11_26_165929_add_service_record.php, tests/Feature/Forms/UpdateGamePanel/ValidGameUpdateTest.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php, tests/Mocks/Xuid/MockXuidService.php
Stellur renamed, dropped the leading S and broke Leaf.
fixes: #170
=> Support XBL Renames

app/Http/Livewire/ChampionshipBracket.php
=> fix: order rounds by number properly

app/Http/Controllers/HomeController.php
=> fix: skip profiles w/ no score on homepage

README.md, app/Http/Controllers/Webhook/FaceItController.php, app/Services/FaceIt/Enums/WebhookEvent.php, tests/Feature/Webhooks/IncomingFaceItWebhookTest.php, tests/Mocks/Webhooks/MockChampionshipFinished.php
=> Support "Championship Ended" Webhook

resources/views/livewire/championship-bracket.blade.php
=> feat: add date to championship bracket

.github/workflows/release.yml
Reverts iBotPeaches/LeafApp_Infinite#220
=> Revert "build: bump deployer to rc4"

database/migrations/2021_11_21_175835_add_matches_table.php
=> fix: correct old migration to reflect true production

app/Enums/PlayerTab.php, app/Http/Livewire/MedalsPage.php, resources/sass/app.scss, resources/views/livewire/medals-page.blade.php, resources/views/livewire/overview-page.blade.php, resources/views/partials/global/account_private.blade.php, resources/views/partials/player/navigation.blade.php, resources/views/partials/player/tabs/medals.blade.php, routes/web.php, tests/Feature/Forms/MedalsPage/ValidMedalsPageTest.php
Requested from https://twitter.com/GALACTIC_4k/status/1490483950862553088
=> Ranked medals

app/Http/Controllers/GameController.php, app/Jobs/ExportGame.php, app/Models/GameTeam.php, database/factories/GamePlayerFactory.php, resources/views/livewire/game-page.blade.php, resources/views/partials/game/export_card.blade.php, resources/views/partials/game/team-table.blade.php, routes/web.php, tests/Feature/Exports/ExportGameTest.php
Another Twitter request from [redacted]
=> Export Game (CSV)

app/Console/Commands/PullHaloData.php, app/Enums/Mode.php, app/Http/Livewire/MedalsPage.php, app/Http/Livewire/OverviewPage.php, app/Http/Livewire/PlayerTogglePanel.php, app/Jobs/PullServiceReport.php, app/Models/Player.php, app/Models/ServiceRecord.php, app/Services/Autocode/ApiClient.php, app/Services/Autocode/Enums/Filter.php, app/Services/Autocode/InfiniteInterface.php, app/Support/Session/ModeSession.php, database/factories/PlayerFactory.php, database/factories/ServiceRecordFactory.php, database/migrations/2022_02_07_004937_add_multiple_record_support.php, resources/views/livewire/medals-page.blade.php, resources/views/livewire/player-toggle-panel.blade.php, resources/views/pages/player.blade.php, resources/views/partials/player/toggle_service_mode.blade.php, tests/Feature/Console/PullHaloDataTest.php, tests/Feature/Forms/OverviewPage/ValidOverviewPageTest.php, tests/Feature/Forms/PlayerTogglePanel/ValidPlayerToggleTest.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
=> Support either Ranked or PVP ServiceRecord

webpack.mix.js
=> fix: don't purge custom colors

app/Http/Livewire/GamePage.php, app/Models/Game.php, app/Models/GamePlayer.php, resources/views/livewire/game-page.blade.php
=> refactor: fix use of internalTeamId vs teamId

.github/workflows/laravel.yml, app/Models/Championship.php, app/Models/Matchup.php, app/Models/Medal.php, database/factories/MedalFactory.php, phpunit.xml, tests/Mocks/Championship/MockChampionshipBracketService.php, tests/Mocks/Championship/MockChampionshipService.php, tests/Mocks/Championship/MockMatchupService.php, tests/Mocks/Csrs/MockCsrAllService.php
=> Remove SQLite

app/Enums/CompetitiveMode.php, app/Http/Livewire/CompetitivePage.php, app/Models/Csr.php, app/Models/Player.php, database/factories/CsrFactory.php, database/migrations/2021_11_26_111551_add_competitive_table.php, database/migrations/2022_02_21_105933_tweak_csr_for_all_modes.php, database/migrations/2022_02_21_112301_remove_fk_csrs.php, database/migrations/2022_02_21_113039_remake_csr_fks.php, resources/lang/en/enums.php, resources/views/livewire/competitive-page.blade.php, resources/views/partials/player/csr-card-row.blade.php, resources/views/partials/player/csr-minimal-card-row.blade.php, tests/Feature/Forms/CompetitivePage/ValidCompetitivePageTest.php, tests/Feature/Forms/UpdatePlayerPanel/InvalidPlayerUpdateTest.php, tests/Mocks/Csrs/MockCsrAllService.php
=> CSR Rework

app/Http/Controllers/HomeController.php, resources/views/pages/legal.blade.php, routes/web.php, tests/Feature/Pages/LegalPageTest.php
=> Adds Legal for soon Google optional Login

app/Models/Medal.php, database/factories/GamePlayerFactory.php, database/factories/ServiceRecordFactory.php, resources/views/partials/leaderboard/medal/medal-card.blade.php
=> Fix Medal Flake

resources/views/partials/game/team-table.blade.php
Reported via Discord that BTB was not showing MMR.
=> fix: show mmr for playlist matches

app/Models/ServiceRecord.php
=> fix: force kd/kda to float

app/Models/Player.php, tests/Feature/Pages/PlayerPageTest.php
=> Support Loading Player via URL

app/Models/Game.php, app/Models/Gamevariant.php, database/factories/GameFactory.php, database/factories/GamevariantFactory.php, database/migrations/2022_04_19_101328_add_gamevariants_table.php, database/seeders/DatabaseSeeder.php, tests/Mocks/Matches/MockMatchService.php, tests/Mocks/Matches/MockMatchesService.php
=> Fix: Properly use Gamevariants

app/Http/Controllers/Auth/GoogleController.php
=> fix: use intended url for redirects

app/Console/Commands/PullHaloData.php, app/Enums/QueueName.php, app/Jobs/PullCompetitive.php, app/Jobs/PullMmr.php, app/Jobs/PullServiceRecord.php, app/Models/Player.php, app/Services/Autocode/ApiClient.php, app/Services/Autocode/InfiniteInterface.php, database/migrations/2022_04_21_104947_add_mmr_to_players.php, tests/Feature/Console/PullHaloDataTest.php, tests/Feature/Forms/UpdateGamePanel/InvalidGameUpdateTest.php, tests/Feature/Forms/UpdatePlayerPanel/InvalidPlayerUpdateTest.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php, tests/Mocks/Mmr/MockMmrService.php
=> MMR (v1.3.0 endpoint)

resources/views/livewire/medals-page.blade.php, resources/views/partials/game/powerful_medals.blade.php, resources/views/partials/home/random_medal.blade.php, resources/views/partials/player/medals.blade.php
Requested via Okom1 on Discord.
=> feat: add difficulty color type + href to all medal locations

resources/js/app.js, resources/js/partials/dates.js, resources/views/partials/game/game-card.blade.php
Requested via Okom1 on Discord.
=> Local Date/Time on Game Page

resources/views/partials/player/date-link.blade.php
Requested via Okom1 on Discord
=> fix: use absolute date after 24 hours

app/Http/Livewire/GameCustomHistoryTable.php
=> fix: don't show lan in custom games

app/Http/Livewire/CompetitivePage.php, app/Http/Livewire/PlayerTogglePanel.php, app/Models/Player.php, resources/views/livewire/competitive-page.blade.php, resources/views/livewire/player-toggle-panel.blade.php, resources/views/pages/player.blade.php, resources/views/partials/player/csr-card-row.blade.php, storage/app/public/.gitignore
=> Competitive Redesign

app/Models/GamePlayer.php
=> fix: lock accuracy to max 100

app/Jobs/PullAppearance.php, app/Models/Game.php, app/Models/Player.php, database/migrations/2022_06_11_104525_add_is_bot_to_players.php, resources/views/pages/player.blade.php, resources/views/partials/game/team-table.blade.php, resources/views/partials/player/player-card.blade.php, tests/Feature/Jobs/PullAppearanceTest.php
=> Bot Support

app/Models/Game.php, app/Models/Team.php, tests/Feature/Pages/GamePageTest.php
=> Load match via any XUID 

deploy.php
=> fix: make timeout 1200s for deploys due to sitemap generation

database/migrations/2022_07_02_102829_grow_columns_on_sr.php
=> fix: grow columms on service record

app/Services/Autocode/ApiClient.php, app/Services/FaceIt/ApiClient.php, app/Services/Tinify/ApiClient.php, app/Services/XboxApi/ApiClient.php
=> refactor: don't use shared pendingRequest

database/migrations/2023_02_21_012419_add_index_for_where.php
```
Showing rows 0 - 7 (8 total, Query took 1.8959 seconds.
```
(old)
```
Showing rows 0 - 7 (8 total, Query took 0.0005 seconds.
```
(new)
=> perf: improve homepage loading speed

app/Http/Livewire/GameCustomHistoryTable.php, app/Jobs/ExportGameHistory.php, app/Models/Game.php, app/Services/Autocode/ApiClient.php, database/migrations/2023_02_25_122500_cleanup_lan_issue.php, tests/Feature/Exports/ExportMatchHistoryTest.php
=> Correct LAN data mismatch

app/Http/Livewire/MedalsLeaderboard.php, database/migrations/2023_02_25_124855_indexes_for_service_records.php
=> Improve performance on medals

app/Http/Controllers/Webhook/FaceItController.php, app/Services/FaceIt/Enums/WebhookEvent.php, tests/Feature/Webhooks/IncomingFaceItWebhookTest.php, tests/Mocks/Webhooks/MockMatchObjectCreated.php
This will allow us to see pending matches (ie scheduled) but not yet over.
=> Feat: FaceIt 'match_object_created' support.

app/Enums/PlayerTab.php, app/Http/Livewire/ModePage.php, app/Http/Livewire/UpdatePlayerPanel.php, app/Models/Player.php, app/Support/Modes/ModeDecorator.php, app/Support/Modes/ModeResult.php, resources/views/livewire/mode-page.blade.php, resources/views/livewire/player-toggle-panel.blade.php, resources/views/livewire/update-player-panel.blade.php, resources/views/pages/player.blade.php, resources/views/partials/player/mode-table.blade.php, resources/views/partials/player/navigation.blade.php, resources/views/partials/player/tabs/modes.blade.php, routes/web.php, tests/Feature/Forms/ModePage/ValidModePageTest.php, tests/Feature/Pages/PlayerPageTest.php
=> Best/Worse Game Modes

app/Http/Controllers/Webhook/FaceItController.php, app/Services/FaceIt/Enums/WebhookEvent.php, tests/Feature/Webhooks/IncomingFaceItWebhookTest.php, tests/Mocks/Webhooks/MockChampionshipStarted.php
=> Add FaceIt 'championship_started' support

app/Http/Controllers/Webhook/FaceItController.php, app/Services/FaceIt/Enums/WebhookEvent.php, tests/Feature/Webhooks/IncomingFaceItWebhookTest.php, tests/Mocks/Webhooks/MockChampionshipCancelled.php
=> feat: FaceIt Webhook: 'championship_cancelled'

resources/views/livewire/mode-page.blade.php
=> fix: correct spelling mistake

resources/views/partials/hcs/matchup_breakdown.blade.php, resources/views/partials/hcs/team_snippet/4v4.blade.php
=> fix: support rendering in-progress 4v4 matchup

app/Enums/AnalyticKey.php, app/Enums/AnalyticType.php, app/Http/Livewire/TopTenLeaderboard.php, app/Jobs/ProcessAnalytic.php, app/Models/Analytic.php, app/Support/Analytics/BaseMapStat.php, app/Support/Analytics/Stats/MostQuitMap.php, app/Support/Analytics/Traits/HasMapExport.php, database/factories/AnalyticFactory.php, database/migrations/2023_03_28_222943_add_map_id_to_analytics.php, resources/views/livewire/top-ten-leaderboard.blade.php, tests/Feature/Jobs/ProcessAnalyticTest.php, tests/Feature/Stats/MostQuitMapTest.php, tests/Traits/HasAnalyticDataProvider.php
=> New Stat: Most Quit Maps

database/migrations/2023_04_01_190024_add_is_cheater_index.php
=> feat: add index for 'is_cheater' to help leaderboards

app/Http/Controllers/Webhook/FaceItController.php, tests/Feature/Webhooks/IncomingFaceItWebhookTest.php, tests/Mocks/Championship/MockChampionshipService.php, tests/Mocks/Webhooks/MockChampionshipCancelled.php, tests/Mocks/Webhooks/MockChampionshipCreated.php, tests/Mocks/Webhooks/MockChampionshipFinished.php, tests/Mocks/Webhooks/MockChampionshipStarted.php, tests/Mocks/Webhooks/MockMatchObjectCreated.php, tests/Mocks/Webhooks/MockMatchStatusFinished.php
* Issues updates to Championship from returned Webhook
* Adds assertion for cancelled event to assert working
=> Fix: Correct handling updates to FaceIt Championship

deploy.php
=> fix: 1800 seconds on deploy

app/Jobs/PullCompetitive.php, app/Jobs/PullServiceRecord.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
=> fix: fallback to latest season if null

app/Http/Livewire/UpdateGamePanel.php, app/Http/Livewire/UpdatePlayerPanel.php
This will help find HaloDotAPI errors quicker :)
=> fix: properly bubble upstream errors to sentry

app/Enums/FaceItStatus.php, resources/lang/en/enums.php
=> fix: add more faceit enums

database/migrations/2023_04_19_104829_make_final_score_signed.php
=> fix: make 'final_score' signed

app/Console/Commands/RefreshMedals.php, app/Console/Kernel.php, app/Enums/Mode.php, app/Http/Livewire/MedalsLeaderboard.php, app/Jobs/ProcessMedalAnalytic.php, app/Models/MedalAnalytic.php, database/factories/MedalAnalyticFactory.php, database/factories/MedalFactory.php, database/migrations/2023_04_29_101818_add_medal_analytics.php, resources/views/livewire/medals-leaderboard.blade.php, resources/views/pages/medal-leaderboard.blade.php, tests/Feature/Console/RefreshMedalsTest.php, tests/Feature/Jobs/ProcessMedalAnalyticTest.php, tests/Feature/Pages/LeaderboardMedalTest.php, tests/Unit/Models/MedalAnalyticTest.php
* Preprocessed nightly
* top 1k export
* only store top 100
=> Medal Redo

app/Models/ServiceRecord.php
Don't mark a profile as private if they've never played ranked. - `v Teall v`
=> fix: correct private mode

app/Http/Livewire/GameCustomHistoryTable.php, app/Http/Livewire/GameHistoryTable.php
=> perf: is whereNull/whereNotNull instead of checking relation

app/Models/ServiceRecord.php
=> fix: ensure total_score cannot be negative

app/Models/Level.php, database/migrations/2023_05_16_110144_add_unknown_level.php, tests/Feature/Pages/GamePageTest.php
Should fix Zeny's profile due to "odd" games.
=> Support modified custom games with invalid level

composer.lock, yarn.lock
It appears at times Dependabot gets our constraints broken and nothing works.
=> Dependency Update (May 21)

app/Http/Controllers/LeaderboardController.php, app/Http/Livewire/PlaylistPage.php, app/Http/Livewire/TopTenLeaderboard.php, app/Providers/AppServiceProvider.php, app/Support/Schedule/ScheduleTimer.php, app/Support/Schedule/ScheduleTimerInterface.php, resources/views/livewire/playlist-page.blade.php, resources/views/livewire/top-ten-leaderboard.blade.php, resources/views/pages/medal-leaderboard.blade.php, resources/views/pages/topten-leaderboard.blade.php, resources/views/partials/leaderboard/common/next_refresh.blade.php, resources/views/partials/leaderboard/common/notice.blade.php
For some reason `schedule::events` is always empty. Yet what I'm doing seems same as official product - https://github.com/laravel/framework/blob/10.x/src/Illuminate/Console/Scheduling/ScheduleListCommand.php#L53
I need to load the Console Kernel to properly init/load data.
=> Time till next refresh

app/Console/Commands/PullMetadata.php, app/Models/Player.php, app/Models/Rank.php, app/Services/HaloDotApi/ApiClient.php, app/Services/HaloDotApi/InfiniteInterface.php, database/factories/RankFactory.php, database/migrations/2023_06_22_005112_add_career_ranks.php, database/migrations/2023_06_22_094554_add_career_rank_to_player.php, resources/sass/_progressbar.scss, resources/sass/app.scss, resources/views/partials/player/player-card.blade.php, tests/Feature/Console/PullMetadataTest.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php, tests/Feature/Pages/PlayerPageTest.php, tests/Mocks/CareerRank/MockCareerRankService.php, tests/Mocks/Metadata/MockCareerRankService.php, tests/Unit/Models/PlayerModelTest.php, tests/Unit/Models/RankModelTest.php
=> Feat: Career Rank Support

app/Models/Player.php
Saw someone with 100%, but it was 99.65%
=> fix: use 2 digits rounding

resources/views/partials/player/player-card.blade.php
- Fixed Career Rank image size
- Fixed progress bar spacing
| Before  | After  | 
|---|---|
| ![Capture d’écran 2023-06-22 à 18 18 08](https://github.com/iBotPeaches/LeafApp_Infinite/assets/1816892/8dfa09a3-2717-425f-b021-a50ac2ae09c3) | ![Capture d’écran 2023-06-22 à 18 14 59](https://github.com/iBotPeaches/LeafApp_Infinite/assets/1816892/97eefb33-c67e-4d8e-92a4-33bcf9682eee) |
=> feat: Updated player-card.blade.php layout

resources/views/livewire/player-card.blade.php
=> fix: prevent overflow on progress wrapper

resources/views/livewire/competitive-page.blade.php, tests/Unit/Models/CsrModelTest.php
Since we introduced support for text on progress bar during XP rework. Lets backport this to the CSRs.
=> refactor: add text to progress bars on csrs

app/Jobs/ProcessAnalytic.php, app/Models/Analytic.php, database/migrations/2023_06_29_101044_add_place_to_analytics.php
Need to split into 2 PRs, so we get the data into system so we don't break charts between time of run and deploy.
=> feat: store top 1k into db for analytics

app/Models/Player.php
=> fix: don't cast null to int for next player rank id

app/Enums/AnalyticKey.php, app/Models/Analytic.php, app/Support/Analytics/Stats/MostGamesPlayedServiceRecord.php, app/Support/Analytics/Stats/MostScoreServiceRecord.php, tests/Traits/HasAnalyticDataProvider.php
Requested from Wolly on Twitter/X
=> feat: add most games / most score

app/Http/Livewire/CompetitivePage.php
=> fix: don't include mmr that is zero

app/Http/Livewire/UpdatePlayerPanel.php, app/Models/Player.php, config/services.php, database/migrations/2023_08_11_095401_add_is_botfarmer_to_players.php, resources/views/pages/player.blade.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
refs #932 
---
Phase 1 so we can see if this is too aggressive or not, then will lodge it into analytic updates later.
=> Detect Bot Farmers

app/Jobs/ProcessMedalAnalytic.php, app/Support/Analytics/Stats/BestAccuracyServiceRecord.php, app/Support/Analytics/Stats/BestKDAServiceRecord.php, app/Support/Analytics/Stats/BestKDServiceRecord.php, app/Support/Analytics/Stats/HighestScoreInRankedGame.php, app/Support/Analytics/Stats/MostBetrayalsServiceRecord.php, app/Support/Analytics/Stats/MostGamesPlayedServiceRecord.php, app/Support/Analytics/Stats/MostKillsInRankedGame.php, app/Support/Analytics/Stats/MostKillsServiceRecord.php, app/Support/Analytics/Stats/MostMedalsInGame.php, app/Support/Analytics/Stats/MostMedalsServiceRecord.php, app/Support/Analytics/Stats/MostScoreServiceRecord.php, app/Support/Analytics/Stats/MostXpPlayer.php
=> fix: prevent bot farmers from the leaderboards

app/Jobs/ProcessAnalytic.php, tests/Feature/Jobs/ProcessAnalyticTest.php
The Top Ten will share places if they have same value.
=> fix: support ties in top-ten

app/Http/Controllers/ScrimController.php, app/Http/Livewire/ScrimPlayers.php, app/Jobs/ExportScrimPlayers.php, app/Support/Scrim/ScrimDecorator.php, resources/views/partials/scrim/tabs/players.blade.php, routes/web.php, tests/Feature/Exports/ExportScrimPlayersTest.php
Requested on Twitter via Clutch
=> Feat: Support CSV Export for Scrim Players

app/Enums/AnalyticKey.php, app/Models/Analytic.php, app/Support/Analytics/Stats/HighestScoreInUnrankedGame.php, tests/Feature/Jobs/ProcessAnalyticTest.php, tests/Traits/HasAnalyticDataProvider.php
=> Highest Score (Unranked) in Top Ten

app/Http/Livewire/GameBadges.php, app/Models/Game.php, resources/views/livewire/game-badges.blade.php, resources/views/livewire/game-page.blade.php, tests/Feature/Forms/GameBadges/AnalyticGameBadgeTest.php, tests/Feature/Forms/GameBadges/EmptyGameBadgeTest.php, tests/Feature/Forms/PlayerBadges/AnalyticPlayerBadgeTest.php, tests/Feature/Forms/PlayerBadges/EmptyPlayerBadgeTest.php
=> Game Badges

resources/views/partials/player/navigation.blade.php
- its causing insane server load
=> fix: temporarily remove modes tab

database/migrations/2023_10_15_101405_add_index_to_is_ranked.php
=> perf: add index on "is_ranked"

app/Support/Modes/ModeDecorator.php
* Unique out the maps and gametypes (faster)
* Pre-query games down to the user one.
Takes 2.1 seconds now instead of 7min
=> perf: pre-filter gameIds by user

resources/views/partials/player/navigation.blade.php
Reverts iBotPeaches/LeafApp_Infinite#1024
=> Revert "fix: temporarily remove modes tab"

app/Http/Controllers/RankController.php, app/Livewire/RanksPage.php, app/Models/Player.php, resources/views/livewire/ranks-page.blade.php, resources/views/pages/ranks.blade.php, resources/views/partials/global/navigation.blade.php, resources/views/partials/ranks/player-card.blade.php, resources/views/partials/ranks/rank-item.blade.php, routes/web.php, tests/Feature/Forms/RanksPage/LoggedUserRankPageTest.php, tests/Feature/Pages/RanksPageTest.php
Design kinda sucks. Tough to fit all information without tooltips and the query to group each user into their own level is inefficient.
fixes: https://github.com/iBotPeaches/LeafApp_Infinite/issues/835
=> Ranks Page

app/Console/Kernel.php, app/Livewire/TopTenLeaderboard.php, app/Support/Schedule/ScheduleTimer.php
We almost have 100 Heroes. We don't need this fast refresh anymore.
=> fix: move most xp back to nightly

resources/views/partials/global/navigation.blade.php
=> fix: remove 'ranks' tab

app/Enums/Bracket.php, app/Enums/ChampionshipType.php, app/Livewire/ChampionshipBracket.php, app/Support/Bracket/BracketDecorator.php, app/Support/Bracket/BracketResult.php, resources/views/livewire/championship-bracket.blade.php, resources/views/partials/hcs/bracket_table/summary.blade.php, resources/views/partials/hcs/navigation.blade.php, resources/views/partials/hcs/navigation/swiss.blade.php, tests/Feature/Pages/HcsBracketPageTest.php, tests/Feature/Pages/HcsMatchupPageTest.php
=> LVT - Swiss Support

package-lock.json, package.json
=> build: sync packages to latest

app/Models/Matchup.php, resources/views/partials/player/ban-header.blade.php, resources/views/partials/player/date-link.blade.php, resources/views/partials/player/mmr-card-row.blade.php
This was causing negative numbers - Carbon3 called it out.
> https://carbon.nesbot.com/docs/#api-carbon-3
=> fix: support absolute default change on carbon3

routes/web.php
Prevent spiders doing dumb stuff.
=> fix: prevent ".git" as a valid round number

package-lock.json, package.json, vite.config.js
This is causing too many issues on deploy. Users are annoyed.
Laravel has no cache busting for manifest.json and restarting fpm or nginx solves nothing.
=> fix: remove sri

resources/views/pages/errors/429-ban.blade.php, resources/views/pages/errors/429.blade.php
Someone thought this was an error message. So this should explain its a simple rate limit and ask for a donation.
=> chore: adjust rate limit message

app/Models/Player.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
This should be must faster.
fixes: #1285
=> Optimize "Bot Farmer" detection

app/Console/Commands/CreateOverview.php, app/Console/Commands/RefreshManualOverviews.php, app/Enums/BaseGametype.php, app/Enums/OverviewType.php, app/Http/Controllers/OverviewController.php, app/Jobs/ProcessOverviewAnalytic.php, app/Livewire/OverviewCard.php, app/Livewire/OverviewsTable.php, app/Models/Overview.php, app/Support/Gametype/GametypeHelper.php, database/migrations/2024_04_28_154604_add_is_custom_to_overviews.php, resources/lang/en/enums.php, resources/views/livewire/overviews-table.blade.php, resources/views/pages/overviews.blade.php, routes/web.php, tests/Feature/Console/CreateOverviewTest.php, tests/Feature/Console/RefreshManualOverviewsTest.php, tests/Feature/Console/RefreshOverviewsTest.php
Requested/Donated via UneeqTV.
=> Custom Overviews

composer.lock, package-lock.json
Can't trust Dependabot all the time to keep these right :/
=> build: update deps (June 20)

database/migrations/2024_07_20_023304_grow_total_seconds_played.php
=> fix: grow overview_stats total_seconds played

resources/views/pages/home.blade.php, resources/views/partials/home/h2_lvl55.blade.php
This reverts commit 307f26d1c9fb807eec841a14887cc6758afbe036.
=> Revert "feat: add lvl55 gg callout (#1463)"

app/Models/Player.php, app/Support/Analytics/BaseGameStat.php, config/services.php
Top Ten was full with 3rd person FF
=> chore: ignore 3p ff from leaderboards

public/robots.txt
Listen you POS ClaudeBot - You used 2TB of my traffic just scanning the same pages over and over and over and over again. Don't respect TTLs?
Rules for thee, not for me?
Blocked.
```
root@deltatap:/var/log/nginx# tail -f access.log -n500 | grep 'ClaudeBot'
18.118.151.112 - - [06/Jan/2025:22:00:58 +0000] "GET /index.php/player/MBchief1994/medals HTTP/1.1" 200 17647 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)"
3.139.93.209 - - [06/Jan/2025:22:00:59 +0000] "GET /index.php/game/2f78fa4c-42f1-401c-a465-c053a4fce9ec HTTP/1.1" 200 4226 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)"
3.139.93.209 - - [06/Jan/2025:22:00:59 +0000] "GET …
```
=> build: ban ClaudeBot from accessing site

.github/workflows/laravel.yml, app/Models/MatchupTeam.php, app/Models/Player.php, composer.json, composer.lock, database/schema/mysql-schema.sql, docker-compose.yml, package-lock.json, phpunit.xml
We don't have an official MariaDB binary set on actions yet, so force mysql to get the mysql dump restore working.
=> feat: Laravel 12

app/Livewire/UpdatePlayerPanel.php, app/Models/Player.php, config/services.php, database/migrations/2025_04_04_172701_add_is_throttled_to_players.php, resources/views/pages/player.blade.php, tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php, tests/Feature/Pages/PlayerPageTest.php
=> feat: add "is_throttled"

app/Actions/Playlist/HashRotations.php, app/Models/Playlist.php, app/Models/PlaylistChange.php, database/factories/PlaylistChangeFactory.php, database/factories/PlaylistFactory.php, database/migrations/2025_04_12_211540_add_historic_playlist_rotations.php, tests/Feature/Console/PullMetadataTest.php, tests/Unit/Actions/HashRotationTest.php, tests/Unit/Models/PlaylistChangeTest.php
I need history of playlist changes, then I'll build a UI for it.
=> feat: store playlist rotation history

.github/workflows/laravel.yml
* Don't run PHPStan with xdebug....
* Run Pint in Parallel mode.
* Run lints and tests in parallel.
=> feat: speed up tests
