iBotPeaches/LeafApp_Infinite

app/Models/Csr.php
database/migrations/2021_11_28_234442_add_start_tier_to_csr.php
resources/views/livewire/competitive-page.blade.php
tests/Feature/Forms/CompetitivePage/ValidCompetitivePageTest.php

Turns out taking current / total, makes each level closer to 99% because if you are at 1250 / 1300. That is pretty much 99%, but the 50 SR climb is still real. 
(old)
(new)

Fix CSR Progress Bars

---

app/Models/GamePlayer.php

Somehow SNlPEDRONE has 4 shots hit, 3 shots made in a game. This results in the API returning -1 as the missed property, which failed db constraints.
```
[2021-11-29 01:33:25] production.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'shots_missed' at row 1 (SQL: insert into `game_players` (`player_id`, `game_id`, `rank`, `outcome`, `kd`, `kda`, `score`, `kills`, `deaths`, `assists`, `betrayals`, `suicides`, `vehicle_destroys`, `vehicle_hijacks`, `medal_count`, `damage_taken`, `damage_dealt`, `shots_fired`, `shots_landed`, `shots_missed`, `accuracy`, `rounds_won`, `rounds_lost`, `rounds_tied`, `kills_melee`, `kills_grenade`, `kills_headshot`, `kills_power`, `assists_emp`, `assists_driver`, `assists_callout`) values (44, 5564, 6, 2, 0.16666666666667, …
```

fix: handle edge case with negative shots missed

---

resources/views/livewire/game-page.blade.php
tests/Feature/Pages/GamePageTest.php

Corrects pages where a few known players are in game, but not rest.

refactor: force update report if no "queue"

---

app/Models/Playlist.php
app/Models/Traits/HasPlaylist.php
app/Services/Autocode/ApiClient.php
database/migrations/2021_12_15_115237_add_playlist_id_to_games.php
resources/views/livewire/game-history-table.blade.php
resources/views/partials/game/game-card.blade.php
tests/Feature/Console/PullHaloDataTest.php
tests/Feature/Forms/GameHistoryTable/ValidGameHistoryTableTest.php
tests/Feature/Forms/UpdatePlayerPanel/InvalidPlayerUpdateTest.php
tests/Feature/Forms/UpdatePlayerPanel/ValidPlayerUpdateTest.php
tests/Feature/Pages/GamePageTest.php
tests/Mocks/Matches/MockMatchesService.php

The API removed `$total` from history, which is what Leaf used to know when games were missing. This removal broke nearly everything, so had to refactor the entire pulling of match history.

Refactor Playlists

---

resources/views/livewire/overview-page.blade.php

This fixes an issue when we emit a Livewire refresh and there was no main div, so it could not refresh the 2nd div (medals) until a manual refresh.

fix: allow auto-refresh with medal information on overview

---

resources/views/partials/player/medals.blade.php

This prevents longer medals from having dual newlines due to long medal name.

fix: use block vs explicit br tag

---

app/Jobs/PullMatchHistory.php

fix: don't let match history timeout after 60s

---

app/Services/Autocode/ApiClient.php

ServiceRecord is taking awhile to parse.

fix: bump to 180s timeout for HaloDotAPI

---

app/Http/Livewire/GamePage.php

Not sure when this happened. Noticed a donation that mentioned it broke.
My gut is that a Laravel upgrade changed how `groupBy` works and it now implicitly keys by the `groupBy` key, when in the past we used the internal_team_id, which swapped between 0/1. Since those are the same keys that were implicitly used as indexes in PHP go 0,1,2. We never noticed.
This needs a better investigation, but grouping by the internal key is working for a quick fix.
refs: #256

fix: groupBy implicit keys by groupBy key

---

resources/sass/app.scss
resources/views/partials/game/game-card.blade.php
resources/views/partials/player/csr-card-row.blade.php

- Respect images ratio (CSR + Map)
- Added a default padding on body (better render on mobile)
| CSR      | Profile | Match  |
| ----------- | -----------  | ----------- |
| ![Capture d’écran 2022-06-09 à 21 02 41](https://user-images.githubusercontent.com/1816892/172926528-375e3624-268d-42a4-968f-5b23569b35e1.png)      | ![Capture d’écran 2022-06-09 à 21 11 17](https://user-images.githubusercontent.com/1816892/172926573-e1c3980e-c467-4575-b00d-39b349a1e880.png)       | ![Capture d’écran 2022-06-09 à 21 11 42](https://user-images.githubusercontent.com/1816892/172926603-458095a2-56a8-4ed7-8d26-c32e4c17d6c5.png)       |

feat: CSS Updates

---

resources/views/partials/hcs/team_snippet/ffa.blade.php

fix: fallback to observer icon if none found

---

tests/Feature/Console/PullChampionshipTest.php
tests/Feature/Forms/AddGamer/InvalidGamerFormTest.php
tests/Feature/Forms/OverviewPage/ValidOverviewPageTest.php
tests/Feature/Pages/HcsBracketPageTest.php
tests/Feature/Pages/HcsMatchupPageTest.php
tests/Feature/Pages/PlayerPageTest.php
tests/Traits/HasAnalyticDataProvider.php
tests/Unit/Models/CsrModelTest.php
tests/Unit/Models/GameTeamModelTest.php
tests/Unit/Support/CsrHelperTest.php

This was odd, missed it during L10 upgrade because I only ran `php artisan test` which hides these deprecations. Reported a bug upstream to Laravel and might attempt a fix when done with HCS upgrades.
https://github.com/laravel/framework/issues/46168

test: remove phpunit deprecations

---

composer.json
composer.lock
yarn.lock

Normally let Dependabot do this, but it upgraded a bogus version which then broke CI when it was reverted - https://github.com/laravel/horizon/issues/1257

Dependency Update (March 11)

---

app/Console/Kernel.php

This didn't appear to work.
Looks like recently merged by @cleptric in https://github.com/getsentry/sentry-laravel/pull/659 and can't quite spot my mistake. Macros must not be loading somehow.
https://leaf-hi.sentry.io/share/issue/0971d4b094e54beca3fe5a78b3a1581d/
---
Will revisit in weekend.

fix: remove cron monitoring

---

app/Http/Controllers/GameController.php
app/Models/Playlist.php
database/factories/PlaylistFactory.php
database/migrations/2023_03_25_171951_drop_thumbnail_from_playlist.php

This is only used in SEO and the URL shifts between seasons. So we are hammering updates to a column we don't use.

fix: remove "thumbnail_url" from playlist

---

app/Models/Playlist.php

Everytime we save information it finds `is_ranked` is 0/1, but we compare to true/false and thus its marked as dirty. This means we have playlists saving non-stop and leading to locks/etc.
Refs: #563

fix: prevent "is_ranked" being marked as dirty

---

app/Models/Game.php

Default a game to non-ffa, because the game player endpoint no longer returns the team. So we don't know until team of match pull.

fix: default a game to non-ffa

---

app/Models/Game.php

This no longer works because of FFA. The name does not exist on match history, but does on match.

fix: correct issue with re-pulling games

---

app/Jobs/ExportGameHistory.php
app/Models/Traits/HasMedals.php
app/Providers/RouteServiceProvider.php

* Stupidly didn't key my rate limit, so it was a system wide shared limit (now by ip)
* Warmed medal cache so its a bit quicker
* Fixed query returning all joined tables so its a bit quicker
* All 5 per hour instead of 1.

Fix CSV Export w/ Rate Limit

---

app/Console/Kernel.php
app/Http/Livewire/TopTenLeaderboard.php
app/Jobs/ProcessAnalytic.php
resources/views/livewire/top-ten-leaderboard.blade.php

feat: put top 100 into pagination

---

app/Support/Analytics/Stats/BestAccuracyServiceRecord.php
app/Support/Analytics/Stats/BestKDAServiceRecord.php
app/Support/Analytics/Stats/BestKDServiceRecord.php
app/Support/Analytics/Stats/MostBetrayalsServiceRecord.php
app/Support/Analytics/Stats/MostKillsServiceRecord.php
app/Support/Analytics/Stats/MostMedalsServiceRecord.php
app/Support/Analytics/Stats/MostTimePlayedServiceRecord.php
tests/Feature/Jobs/ProcessAnalyticTest.php

Had a user complain they should be on the service based leaderboards.
Investigate and saw were using the old deprecated `season_number` key.
```
MariaDB [leafapp_infinite]> select id,player_id,mode,season_number,season_key,medal_count from service_records where player_id=407668;
+-------+-----------+------+---------------+------------+-------------+
| id    | player_id | mode | season_number | season_key | medal_count |
+-------+-----------+------+---------------+------------+-------------+
| 82907 |    407668 |    1 |             1 | NULL       |      145247 |
| 88481 |    407668 |    1 |             1 | 1-1        |       10746 |
| 88482 |    407668 |    1 |             1 | 1-2        |       12311 |
| 88483 |    407668 |    1 |             1 | 2-1        |       50224 |
| 88484 | …
```

fix: leaderboards should look for missing season_key

---

app/Http/Livewire/TopTenLeaderboard.php

This will fix a reported issue on Twitter where Uvinity was twice. We only ordered by place with there was 11 - so nothing to enforce the order of those tied places.

fix: allow more than 10 tied places

---

app/Support/Rotations/RotationResult.php
database/factories/PlaylistFactory.php
tests/Mocks/Metadata/MockPlaylistsService.php

This will fix issues where like Fiesta has duplicate Slayer events. We stripped stuff before colon as it was duplicating of playlist name, in this case its not.

feat: support Super-iteration of gametypes on Playlists

---

app/Http/Kernel.php

This should hint to browsers to load our JS so the HTML doesn't have to be processed first.

build: preload js

---

app/Support/Analytics/BaseGameStat.php
app/Support/Analytics/Stats/MostAssistsInGame.php
app/Support/Analytics/Stats/MostDeathsInGame.php
app/Support/Analytics/Stats/MostKillsInGame.php
app/Support/Analytics/Stats/MostKillsWithZeroDeathsGame.php
app/Support/Analytics/Stats/MostMedalsInGame.php
config/services.php

Meant to do this, but forgot about it. Someone on Twitter called out the Top Ten being useless because of FF.

fix: avoid ff matches in top ten

---

resources/views/layouts/app.blade.php

All of Livewire broke somehow - I guess we missed a step in the upgrade guide. Which makes me doubt letting Livewire load itself. We could increase performance by packing that into JS that is handled via nginx.

fix: let livewire load itself

---

app/Models/PlayerBan.php

Twitter person was confused on the wording - since its in perspective of the banned individual. I'll rewrite messages on the fly to their gamertag.

fix: inject gamertag into ban message

---

app/Enums/Experience.php
resources/lang/en/enums.php

Influx of 1k+ failed games due to a new experience type - not sure what it could be. I'll have to find a game and pass to @Alexis-Bize.

fix: add unknown experience

---

resources/views/livewire/championships-table.blade.php
resources/views/livewire/game-custom-history-table.blade.php
resources/views/livewire/game-history-table.blade.php
resources/views/livewire/game-lan-history-table.blade.php
resources/views/livewire/medals-leaderboard.blade.php
resources/views/livewire/medals-table.blade.php
resources/views/livewire/scrims-table.blade.php
resources/views/livewire/top-ten-leaderboard.blade.php
resources/views/livewire/top-ten-table.blade.php

Requested on Twitter to stop moving table on pagination changes.

fix: prevent scrolling on pagination change

---

app/Console/Commands/CheckForUnban.php
app/Models/PlayerBan.php
resources/views/partials/player/ban-header.blade.php
routes/console.php
tests/Feature/Console/CheckForUnbanTest.php

With bans flying like crazy (50+ in 48 hours) I saw some were forever (till year 9999) while others were 6 month bans. This adds support for an expiring ban that checks nightly.

Support for partial bans.

---

app/Jobs/PullAppearance.php
app/Jobs/PullCompetitive.php
app/Jobs/PullLogoFromMatchupTeam.php
app/Jobs/PullMatchHistory.php
app/Jobs/PullServiceRecord.php
app/Jobs/PullXuid.php

This will prevent a job from hitting timeout (getting killed) and retrying, then failing as "max attempts reached". It'll be easier to detect if our timeouts are too small.

fix: treat timeout as failure

---

app/Models/Map.php
resources/views/livewire/game-custom-history-table.blade.php
resources/views/livewire/game-history-table.blade.php
resources/views/livewire/game-lan-history-table.blade.php
resources/views/livewire/top-ten-leaderboard.blade.php
resources/views/partials/game/game-card.blade.php
resources/views/partials/hcs/game_breakdown/ffa.blade.php
resources/views/partials/player/mode-table.blade.php
resources/views/partials/scrim/matches_breakdown/ffa.blade.php
resources/views/partials/scrim/matches_breakdown/team.blade.php

Another request from Twitter to remove the annoying "- Ranked" from map names. While I do agree the Ranked iteration of the maps are different you can determine that from the playlist.

fix: remove "- Ranked" from map name

---

app/Models/Player.php

This pull request includes a change to the `updateFromDotApi` function in the `app/Models/Player.php` file. Three new game playlists have been added to the configuration array: `firefight-grunt-koth`, `firefight-grunt-heroic`, and `firefight-grunt-legendary`.

fix: detect grunt ff for bot farmer detection

---

app/Models/Map.php

* I don't think we should have Husky specific maps - they didn't start that way and normally Husky maps are custom so there is no chance of overlap with others.

fix: strip " - Husky Raid" from map

---

app/Jobs/ProcessOverviewAnalytic.php
app/Support/Gametype/GametypeHelper.php
routes/console.php
tests/Feature/Console/RefreshOverviewsTest.php

This pull request includes changes primarily focusing on the processing of `Overview` analytics and the scheduling of the `RefreshOverviews` command. The most important changes include adding a condition in the `handle` method of `ProcessOverviewAnalytic.php` to skip processing if the `Overview` was updated within the past week, adding a new `Heroic Fiesta` mode to the `findBaseGametype` function in `GametypeHelper.php`, changing the frequency of the `RefreshOverviews` command in `console.php` from weekly to monthly, and adding a new test case in `RefreshOverviewsTest.php` to check the functionality of the new condition in `ProcessOverviewAnalytic.php`.
* [`app/Jobs/ProcessOverviewAnalytic.php`](diffhunk://#diff-5597c74f5f3bdd91b69aab217691278b97c9ac2d44a381aee6cc169a126c7841R51-R58): …

Overfixes processing fixes

---

app/Jobs/ProcessAnalytic.php
app/Support/Analytics/Stats/MostQuitMap.php

Reported by Okom and caused by assuming we'd have at least 1k events in the top ten.

fix: ensure most quit does not include customs

---

app/Models/GamePlayer.php

```
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'assists' at row 1 (Connection: mysql, SQL: insert into `game_players` (`player_id`, `game_id`, `pre_csr`, `post_csr`, `matches_remaining`, `rank`, `outcome`, `was_at_start`, `was_at_end`, `was_inprogress_join`, `kd`, `kda`, `score`, `mmr`, `kills`, `deaths`, `assists`, `betrayals`, `suicides`, `max_spree`, `vehicle_destroys`, `vehicle_hijacks`, `medal_count`, `damage_taken`, `damage_dealt`, `shots_fired`, `shots_landed`, `shots_missed`, `accuracy`, `rounds_won`, `rounds_lost`, `rounds_tied`, `kills_melee`, `kills_grenade`, `kills_headshot`, `kills_power`, `assists_emp`, `assists_driver`, `assists_callout`, `expected_kills`, `expected_deaths`) values (9057, 44266607, ?, ?, ?, 1, 1, 1, 1, 0, 2, 5, 2000, ?, …
```

fix: don't let assists go negative

---

app/Http/Controllers/GameController.php
app/Http/Controllers/HcsController.php
app/Http/Controllers/LeaderboardController.php
app/Http/Controllers/OverviewController.php
app/Http/Controllers/PlayerController.php
app/Http/Controllers/PlaylistController.php

I thought my upstream library did this...Apparently not - https://github.com/artesaos/seotools/issues/326

fix: escape contents for SEO library

---

app/Models/Player.php
app/Support/Analytics/BaseGameStat.php
config/services.php

This should knock the top ten (no deaths) back into normal.

fix: ignore new ff playlist (Battle 4 Reach)

---

app/Models/PlayerBan.php
database/migrations/2025_01_11_140745_reprocess_hash_ban_keys.php

Improperly used end date instead of player for hash key to de-dupe.

fix: use message + player for ban hash

---

app/Support/Gametype/GametypeHelper.php

```
Processed Harvesters in 0 seconds.
In GametypeHelper.php line 108:
Unable to find base gametype for: Hex A Gone  
leaf@deltatap:/var/www/leaf/current$ 
```

fix: "Hex A Gone"

---

app/Livewire/AddGamerForm.php
resources/views/livewire/add-gamer-form.blade.php
resources/views/partials/global/navigation.blade.php

This PR adds the gamertag search functionality to the navigation bar, allowing users to search for gamertags from any page except the homepage. This addresses user feedback about having to return to the homepage to perform new searches.
- Added gamertag search to navbar using existing AddGamerForm Livewire component
- Improved validation UX by resetting validation state when modifying failed entries
- Created conditional rendering for navbar vs homepage search components
- Added `isNav` property to AddGamerForm Livewire component to control rendering context
- Modified validation behavior to clear error states when user modifies input after a failed validation
- Adjusted component styling for navbar context:
- Removed section/header elements
- Removed info messages
- Added permanent …

Add Gamertag search to Navigation Bar

---

app/Support/Gametype/GametypeHelper.php
tests/Feature/Console/RefreshOverviewsTest.php

A lot of gametypes suck with names - pure "Arena" or "Classic". For those we can fallback to base gametype to identify.

fix: add 'Classic' gamemode, fallback to category

---

resources/views/livewire/banned-player-table.blade.php
resources/views/livewire/medals-leaderboard.blade.php
resources/views/livewire/top-ten-leaderboard.blade.php
resources/views/pages/player.blade.php
resources/views/partials/game/team-table.blade.php
resources/views/partials/home/recently_updated.blade.php

Since some bans are chat bans, etc. I'm rebranding this to "Banned"

fix: refer to "Cheater" as "Banned"

---

app/Console/Commands/RefreshMedals.php
routes/console.php
tests/Feature/Console/RefreshMedalsTest.php

We are running nearly 15 seasons and ALL every single night. It never catches up. This moves the seasons to a weekly check, but keeps the ALL (total) for daily.

perf: only re-run all seasons weekly on medal stats

---

app/Console/Commands/CheckForBan.php
app/Services/DotApi/ApiClient.php
database/factories/PlayerBanFactory.php
tests/Feature/Console/CheckForBanTest.php

A user's ban expired, a "ban check" re-banned them. This fixes that.

fix: don't reban users if they have a historic ban
